/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barcode.reader;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EssamAlmutair
 */
public class Statestics extends javax.swing.JFrame {

    /**
     * Creates new form Statestics
     */
    public Statestics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        value = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chooseEvent = new javax.swing.JButton();
        ChosenEvent = new javax.swing.JTextField();
        Choose = new javax.swing.JButton();
        ComboChoose = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ComboShow = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        selectedField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton2.setText("الصفحة الرئيسية");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel4.setText("المجموع الكلي لـ");

        jLabel2.setText("للعرض المخصص");

        chooseEvent.setText("اختر النشاط");
        chooseEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseEventActionPerformed(evt);
            }
        });

        ChosenEvent.setBackground(new java.awt.Color(204, 204, 204));
        ChosenEvent.setText("تلقائي");
        ChosenEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChosenEventActionPerformed(evt);
            }
        });

        Choose.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 12)); // NOI18N
        Choose.setText("عرض");
        Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseActionPerformed(evt);
            }
        });

        ComboChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "جميع أعضاء هيئة التدريس", "جميع موظفي الكلية", "جميع الطلاب", "جميع الضيوف" }));
        ComboChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboChooseActionPerformed(evt);
            }
        });

        jLabel1.setText("عرض إحصائيات الحضور والأنشطة");

        jButton1.setText("عرض");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TableMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        ComboShow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " الأنشطة", " الطلاب", "أعضاء هيئة التدريس", " موظفي الكلية", "الضيوف" }));
        ComboShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboShowActionPerformed(evt);
            }
        });

        jLabel3.setText("في النشاط");

        selectedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("مساوي لـ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectedField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ComboChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Choose, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ComboShow, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(jButton1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ChosenEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(chooseEvent))))))))
                .addGap(6, 116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ChosenEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseEvent))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Choose)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(selectedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboShowActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_ComboShowActionPerformed

    private void execute2(ArrayList<Event> item, int selectedNumber) {

        //To show all events 
        DefaultTableModel model = new DefaultTableModel();
        String[] column = {"الوقت", "التاريخ ", "نوع النشاط ", " اسم النشاط", " رقم النشاط"};
        int count = item.size();
        model.setColumnIdentifiers(column);
        for (int i = 0; i < count; i++) {

            String name = item.get(i).getName();
            String id = Integer.toString(item.get(i).getEventId());
            String type = item.get(i).getType();
            String date = item.get(i).getType();
            String time = item.get(i).getType();
            String[] row = {time, date, type, name, id};
            model.addRow(row);

        }

        Table.setModel(model);//show selected Event in the textfield    

    }

    private void execute(ArrayList<User> item, int a) {

        DefaultTableModel model = new DefaultTableModel();
        String[] column = {"النوع", "القسم ", "الكلية", " الأسم", " الرقم المعرف"};
        int count = item.size();
        model.setColumnIdentifiers(column);
        for (int i = 0; i < count; i++) {

            String name = item.get(i).getName();
            String id = Integer.toString(item.get(i).getId());
            String college = item.get(i).getCollege();
            String date = item.get(i).getType();
            String time = item.get(i).getType();
            String[] row = {time, date, college, name, id};
            model.addRow(row);

        }

        Table.setModel(model);//show selected Event in the textfield

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String showFromCombo = ComboShow.getSelectedItem().toString();//To get selected item from عرض
        selectedField.setText(showFromCombo);//to file the textFiled
        int a = ComboShow.getSelectedIndex();//to determine which kind of show 

        String selectFromCombo = ComboChoose.getSelectedItem().toString();//to get selected item from اختر

        StatOperations stat = new StatOperations();// create opject to execute query

        ArrayList<User> item = null;
        int selectedNumber = 0;//to determine which case to show

        try {
            //جميع الأنشطة
            if (a == 0) {//
                ArrayList<Event> item2 = null;
                //This method to get all the events from database 
                item2 = stat.selectAllEvents();
                int count = item2.size();// To count total number of events;
                selectedNumber = 0;
                int count2 = item2.size();
                execute2(item2, selectedNumber);
                total.setText(Integer.toString(count2));
            } //الطلاب
            else if (a == 1) {
                //this method to get all students
                item = stat.selectAllStudents();

                int count = item.size();// To count total number of events;
                execute(item, selectedNumber);
                total.setText(Integer.toString(count));
            } //أعضاء هيئة التدريس
            else if (a == 2) {

                //this method to getall people
                item = stat.selectAllProfessor();

                int count = item.size();// To count total number of events;
                execute(item, selectedNumber);
                total.setText(Integer.toString(count));
            } //موظفي الكلية
            else if (a == 3) {

                //This method to get all users
                item = stat.selectAllStaff();

                int count = item.size();// To count total number of events;
                execute(item, selectedNumber);
                total.setText(Integer.toString(count));
            } //الضيوف
            else if (a == 4) {
                //this method to get all guests
                item = stat.selectAllGuests();

                int count = item.size();// To count total number of events;
                execute(item, selectedNumber);
                total.setText(Integer.toString(count));
            }

        } catch (SQLException ex) {
            Logger.getLogger(Statestics.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseActionPerformed
        // TODO add your handling code here:
        int selected = ComboChoose.getSelectedIndex();

        int count = 0;
        ArrayList<User> item = null;
        StatOperations stat = new StatOperations();
        String event=ChosenEvent.getText();//to chose which event
        int selectedNumber = 0;//to determine which case to show(students, professors,staffs)
        //أعضاء هيئة التدريس
        if (selected == 0) {
            try {

                //this method to getall professors in specific event
                item = stat.selectAllProfessor2(event);
                count = item.size();// to count total of professors
                execute(item, selectedNumber);

            } catch (SQLException ex) {
                Logger.getLogger(Statestics.class.getName()).log(Level.SEVERE, null, ex);
            }
            count = item.size();// To count total number of events;
            total.setText(Integer.toString(count));

        } //موظفي الكلية
        else if (selected == 1) {

            try {
                //this method to getall professors in specific event
                item = stat.selectAllStaff2(event);
            } catch (SQLException ex) {
                Logger.getLogger(Statestics.class.getName()).log(Level.SEVERE, null, ex);
            }

            execute(item, selectedNumber);

            count = item.size();// To count total number of staff;
            total.setText(Integer.toString(count));


        } //الطلاب
        else if (selected == 2) {

              try {
                //this method to getall professors in specific event
                item = stat.selectAllStudents2(event);
            } catch (SQLException ex) {
                Logger.getLogger(Statestics.class.getName()).log(Level.SEVERE, null, ex);
            }

            execute(item, selectedNumber);

            count = item.size();// To count total number of staff;
            total.setText(Integer.toString(count));
        } //الضيوف
        else if (selected == 3) {
            
              try {
                //this method to getall professors in specific event
                item = stat.selectAllGuests2(event);
            } catch (SQLException ex) {
                Logger.getLogger(Statestics.class.getName()).log(Level.SEVERE, null, ex);
            }

            execute(item, selectedNumber);

            count = item.size();// To count total number of staff;
            total.setText(Integer.toString(count));
            
        }
        selectedField.setText(ComboChoose.getSelectedItem().toString());//fill the textfiled with event name
        value.setText(ChosenEvent.getText());//fill the textfiled with event name
    }//GEN-LAST:event_ChooseActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void ComboChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboChooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboChooseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Management mana = new Management();
        mana.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
        


    }//GEN-LAST:event_valueActionPerformed

    private void chooseEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseEventActionPerformed
        // TODO add your handling code here:
        int column = 3;//represent event column in the table
        int row = 0;

        String value = Table.getModel().getValueAt(row, column).toString();//get selected event
        if (value == "") {
            System.out.println("please select an event");
        } else {
            row = Table.getSelectedRow();
            value = Table.getModel().getValueAt(row, column).toString();//get selected event
            ChosenEvent.setText(value);//show event name from the table
        }
    }//GEN-LAST:event_chooseEventActionPerformed

    private void ChosenEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChosenEventActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ChosenEventActionPerformed

    private void TableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_TableMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        StatOperations stat = new StatOperations();
        ArrayList<Event> item2 = null;
        try {
            //This method to get all the events from database for default value
            item2 = stat.selectAllEvents();
        } catch (SQLException ex) {
            Logger.getLogger(Statestics.class.getName()).log(Level.SEVERE, null, ex);
        }
        int count = item2.size();// To count total number of events;
        int selectedNumber = 0;
        int count2 = item2.size();
        execute2(item2, selectedNumber);
        total.setText(Integer.toString(count2));
        int column = 3;//represent event column in the table
        int row = 0;
        ChosenEvent.setText(Table.getModel().getValueAt(row, column).toString());//default value 

    }//GEN-LAST:event_formWindowOpened

    private void selectedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedFieldActionPerformed
        // TODO add your handling code here:
        selectedField.setText(ComboChoose.getSelectedItem().toString());
    }//GEN-LAST:event_selectedFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statestics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statestics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statestics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statestics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statestics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choose;
    private javax.swing.JTextField ChosenEvent;
    private javax.swing.JComboBox<String> ComboChoose;
    private javax.swing.JComboBox<String> ComboShow;
    private javax.swing.JTable Table;
    private javax.swing.JButton chooseEvent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField selectedField;
    private javax.swing.JTextField total;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables

}
